In [1]:
import pandas as pd
import numpy as np

# This code displays all results created within a jupyter notebook cell.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

pd.set_option('display.max_column', 100)
pd.set_option('display.max_row', 200)

In [2]:
data = pd.read_csv('Data_for_prediction.csv', header=0)

In [3]:
data[' Population'].values

array([1250, 1234, 1337, ..., 1435, 1548,  589], dtype=int64)

In [4]:
list(data.columns.values)

['Id',
 'neighborhood',
 'larger_neighborhood',
 'Name',
 ' Population',
 'Median Household Income',
 'Median Home Value',
 'Percent Bachelors Degree',
 'Median Rent',
 'Percent Public Transportation to Work',
 'Percent White Non-Hispanic',
 ' Housing Units',
 'Percent Renter Occupied',
 'Percent Occupied Structure w 3-4 Units',
 'Percent Occupied Structure w 5+ Units',
 'Percent Households w 3 Vehicles',
 'Percent Households w 4+ Vehicles',
 'Percent Families, Married w Children Under 18',
 ' Total Households',
 'Year']

In [32]:
Series_tract_1 = data.loc[data['Name'] == 'BG0001001', ' Population'].values

In [70]:
range(8)

range(0, 8)

In [5]:
Series_tract= []
for j in list(range(480)):
    for i in list(range(8)):
        Series_tract.append(data[' Population'].iloc[j+480*i])

In [6]:
Series = data[[' Population']].values

In [7]:
from pandas import Series
from matplotlib import pyplot
from statsmodels.tsa.ar_model import AR
from sklearn.metrics import mean_squared_error
import numpy

# create a difference transform of the dataset
def difference(dataset):
    diff = list()
    for i in range(1, len(dataset)):
        value = dataset[i] - dataset[i - 1]
        diff.append(value)
    return numpy.array(diff)

# Make a prediction give regression coefficients and lag obs
def predict(coef, history):
        yhat = coef[0]
        for i in range(1, len(coef)):
            yhat += coef[i] * history[-i]
        return yhat

C:\Users\anqwang\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [9]:
Series_tract[0*1:0*1+8] 

[1250, 1279, 1273, 1310, 1352, 1361, 1389, 1401]

In [92]:
Series_tract[0:2]

[1250, 1279]

In [64]:
predictions = [1] * 480
for i in range(480):       
    X = difference(Series_tract[9*i:9*i+8] )
    X
    model = AR(X)
    model_fit = model.fit(maxlag=1, disp=False)
    window = model_fit.k_ar
    coef = model_fit.params
        # walk forward over time steps in test
    history = X[6]   
    predictions[i] =  coef[1]+coef[0]*X[6]  

array([29, -6, 37, 42,  9, 28, 12], dtype=int64)

array([ 53,  25,  -4,  31,  37,  25, -56], dtype=int64)

array([ 16,  61,   4,  38,  27, -18,   8], dtype=int64)

array([  36,   21,   12,   41, -745,    7,   32], dtype=int64)

array([40, 17, 21, 23, 14, 14,  4], dtype=int64)

array([ -6,  51, 141,   8,   8,  63,  -4], dtype=int64)

array([ 14, -12,  32,  17,  32, -11,  65], dtype=int64)

array([-628,   -4,   16,   46,    0,   25,   31], dtype=int64)

array([-6, 49, 33, -4, 12, 52, 23], dtype=int64)

array([ -16,   23,   66,    0,   43,   15, -215], dtype=int64)

array([ 22,  68,  16,   0,   2, -33,  -5], dtype=int64)

array([  31,   15,   27,   10, 1339,   62,   38], dtype=int64)

array([  120,    29,    71, -1771,   -12,    30,    20], dtype=int64)

array([  49,   24, -352,    3,   54,   12,   -3], dtype=int64)

array([  12, -194,   -8,   22,   20,   28,   28], dtype=int64)

array([-429,   -1,    9,   36,   29,   15,   13], dtype=int64)

array([14, 37, 11, -3, 43, 30,  3], dtype=int64)

array([  35,   24,   34,    0,   47,   26, -435], dtype=int64)

array([  17,   12,   31,   37,   23, -513,   -6], dtype=int64)

array([12,  6, 29, 15, 64, 25, -6], dtype=int64)

array([ 23,  21,  19, 224,  34,  27, -12], dtype=int64)

array([  22,   24, -396,   -3,   17,   44,   36], dtype=int64)

array([46, 93, 14,  4, 18, 75, 23], dtype=int64)

array([-57,  20,  -3,  38,  70,   3,  26], dtype=int64)

array([12,  6,  6, 36,  4, -3, 25], dtype=int64)

array([ 24, -17,  53,   2,   6,  26, 151], dtype=int64)

array([  31,   39,   -3,   -8,   73, -620,   22], dtype=int64)

array([  45,   17,   35,   18, -415,   -5,   15], dtype=int64)

array([ -5,  31,  12, -94,  22,   1,  26], dtype=int64)

array([ 31,  17, 178,  26,  24,  -3,  16], dtype=int64)

array([ 37, 118,  30,   4,  12,  58,   6], dtype=int64)

array([-496,   29,   22,    4,   35,   -4,   32], dtype=int64)

array([16, -6, 11, 23, 32, 17,  9], dtype=int64)

array([12, 32, 30,  2,  0, 20, 45], dtype=int64)

array([18, 32,  0, 27, 20, 58, 12], dtype=int64)

array([ 22,  37,  36,  16, -92,  29,  18], dtype=int64)

array([  -2,   41,   22, -170,   12,   14,    8], dtype=int64)

array([  40,   22, -276,   19,   26,   19,   28], dtype=int64)

array([18, 56, 27, 33, -7, 17, 57], dtype=int64)

array([-308,   24,   30,    3,   43,    9,  -10], dtype=int64)

array([-12,  27,  36,  22,  70,  23,  23], dtype=int64)

array([  67,   17,   23,   40,   30,    2, -412], dtype=int64)

array([  14,   57,   21,   22,    6, -132,   22], dtype=int64)

array([   2,   57,   19,   18, -484,   -6,   48], dtype=int64)

array([  48,   20,    9, -125,    1,   40,   12], dtype=int64)

array([ 25,  41, 153,  -9,  25,  19,  71], dtype=int64)

array([   4, -170,   -6,   41,   20,   51,   -8], dtype=int64)

array([-273,  -11,   25,   26,   59,   -1,   27], dtype=int64)

array([27, 26, -5,  9, 53, 28,  4], dtype=int64)

array([  38,   14,   -1,   46,   31,   12, -189], dtype=int64)

array([  36,   30,   18,   33,   29, -104,  -10], dtype=int64)

array([18, 63, 27, 25,  6, 17, 33], dtype=int64)

array([  -1,   40,   -2, -659,    8,    4,   27], dtype=int64)

array([  17,   -7, -128,    7,   20,    4,   35], dtype=int64)

array([16, 83, 14, 11, 46, -1, 56], dtype=int64)

array([-471,    6,   26,    9,    7,   42,   22], dtype=int64)

array([ 7, 28,  8, 26, -1, 17,  4], dtype=int64)

array([  2,  13,  21,  31,  24,  17, 490], dtype=int64)

array([  19,   -1,   44,   30,   22, -170,  -11], dtype=int64)

array([  14,   56,   24,   27, -146,   38,   29], dtype=int64)

array([  47,   46,   30, -219,   38,   23,   28], dtype=int64)

array([  23,   27, -358,   17,   10,   48,  -14], dtype=int64)

array([  26, -269,   -9,   25,   30,   33,    9], dtype=int64)

array([ 86, -11,  55,  30,  32,  28, -14], dtype=int64)

array([17, 12, 18,  0, 33, 13, 35], dtype=int64)

array([ 14,   3,  29,   1,  20,  22, 484], dtype=int64)

array([  70,   35,    6,   28,   39, -805,    1], dtype=int64)

array([ 37,   4,  10,  22, 401,   0,  17], dtype=int64)

array([  18,   25,   28, -102,    2,   30,   49], dtype=int64)

array([  25,   27, -242,   -3,   56,   15,   23], dtype=int64)

array([  48, -347,    0,   39,   -6,   27,   36], dtype=int64)

array([-273,   -8,   22,   43,    5,    9,   38], dtype=int64)

array([22, 21,  5, 31, -2, 23, 25], dtype=int64)

array([  9,  20,  25,  -1,  13,  19, 293], dtype=int64)

array([43, -4, 26, 31,  7, 74, -9], dtype=int64)

array([  38,   32,   38,   16, -173,   30,  -15], dtype=int64)

array([   6,   33,   23, -519,   18,   -5,   42], dtype=int64)

array([ 30,  16, 110, -12,  67, -13,  56], dtype=int64)

array([  28, -129,   29,   26,  -17,   27,   47], dtype=int64)

array([-529,  -10,   34,    4,   19,   35,   28], dtype=int64)

array([-13,  32,  13,  37,  41,  42,  28], dtype=int64)

array([  24,   53,   23,   15,   23,   13, -402], dtype=int64)

array([ 19,  19,  11,  31,   7, 228,  32], dtype=int64)

array([   1,   39,   37,    7, -413,   25,    0], dtype=int64)

array([  24,   34,   12, -434,   -7,   47,    0], dtype=int64)

array([ 28,   9, -15,  27,  18,   8,  -3], dtype=int64)

array([ 22, 314,  -8,  37,  26,  36,  42], dtype=int64)

array([-201,   32,   20,   20,    0,   45,   36], dtype=int64)

array([-11,  48,  31,  51,  -3,  39,  27], dtype=int64)

array([ 8, 28, 31, 20, 39, 25, 60], dtype=int64)

array([  25,   43,   -2,   52,   19, -468,   30], dtype=int64)

array([ 17,  43,  18, -12, -57,  34,  26], dtype=int64)

array([  40,   47,   -9, -262,   28,   23,   14], dtype=int64)

array([  33,   -3, -282,   24,   27,   11,   19], dtype=int64)

array([  38, -190,   -8,   40,   21,   20,    3], dtype=int64)

array([63, -7, 24, 26, 47, 24, 21], dtype=int64)

array([ -4,  58,  -1,  28,  30,  45, -17], dtype=int64)

array([  21,    8,   34,   15,   34,    1, -503], dtype=int64)

array([ 18,  18,   1,  36,  17, 108,  29], dtype=int64)

array([  -8,   52,   19,   22, -194,   -6,   46], dtype=int64)

array([  42,   15,   25, -132,   -7,   29,   14], dtype=int64)

array([  40,   21, -539,   16,   14,    5,    2], dtype=int64)

array([  7, 760,  35,  29,   9,  43,  25], dtype=int64)

array([-608,    7,   16,   14,   29,   36,   22], dtype=int64)

array([-6, 22, 27, 37, 26, 14, 15], dtype=int64)

array([ -3,  17,  40,  15,  18,  33, 441], dtype=int64)

array([  33,   49,   26,   27,  -13, -690,  -10], dtype=int64)

array([  29,   20,   33,   24, -268,   25,   -9], dtype=int64)

array([ 43,  20,  23, -63,  28,  15,  19], dtype=int64)

array([  27,   -8, -112,   21,   28,    5,   21], dtype=int64)

array([  30, -264,   19,   24,   14,   26,   -4], dtype=int64)

array([278,  30,   2,  15,  41,  32,  33], dtype=int64)

array([ 32, -19,  27,  40,  31,  34,  28], dtype=int64)

array([ 12,  29,  23,  35,  18,  12, -59], dtype=int64)

array([  17,   31,   61,   16,   27, -151,   -3], dtype=int64)

array([  44,   19,   21,   25, -156,   -2,   25], dtype=int64)

array([ 31,  13,  38, 372,  24,  48,  22], dtype=int64)

array([  47,   33, -967,   -6,   39,    2,   18], dtype=int64)

array([  14, -271,    3,   37,  -12,   44,    6], dtype=int64)

array([601,  -9,  34,  67,  34,  29,  30], dtype=int64)

array([ -7,  47,  22,  27, -15,  37,  24], dtype=int64)

array([  81,   17,   34,   16,   34,   20, -902], dtype=int64)

array([ 11,  29,   4,  29,   8, 334,  25], dtype=int64)

array([63,  2, 39, 27, 42, 12,  6], dtype=int64)

array([   3,   45,   30, -419,    0,   51,   22], dtype=int64)

array([  50,    7, -411,  -11,   41,   30,   30], dtype=int64)

array([  29, -259,   15,   30,    3,   42,  -12], dtype=int64)

array([-370,    4,   11,   18,   30,   13,   24], dtype=int64)

array([ -6,  72, -17,  32,  47,  44,  20], dtype=int64)

array([  79,   27,  -13,   34,   70,   14, -311], dtype=int64)

array([  31,   16,   46,   44,   -2, -194,  -13], dtype=int64)

array([  -4,   28,   60,   28, -271,   13,    5], dtype=int64)

array([   2,   39,   17, -359,   11,   29,   -7], dtype=int64)

array([  38,   25, -164,    6,   49,    6,    1], dtype=int64)

array([  21, -258,    8,   23,   29,   -2,   22], dtype=int64)

array([747,  14,  41,  40, -30,  36,  45], dtype=int64)

array([ 17,  43, -14,  27,  58,  13,  45], dtype=int64)

array([ 25,  17,  -4,  14,  54,  23, 221], dtype=int64)

array([  48,    0,   66,   34,   34, -237,   -1], dtype=int64)

array([ 20,  48,  37,  37, -35,   2,  51], dtype=int64)

array([  22,   26,   37, -917,    6,   40,  -13], dtype=int64)

array([  2,  43, 380,  35,  34,  13,  25], dtype=int64)

array([  15, -708,   24,   20,   17,   -7,   38], dtype=int64)

array([93, -2, 41, 16, 19, 29, 26], dtype=int64)

array([20, 10, 10,  4, 29, 18,  3], dtype=int64)

array([29, 24, 58, 13, 21, 18, 39], dtype=int64)

array([ 14,  67,  19,  21,  25, 642,  39], dtype=int64)

array([  75,   32,   33,   43, -550,   40,   40], dtype=int64)

array([   52,    31,    37, -1130,    18,    -5,    24], dtype=int64)

array([22, 31, 34, 29, 13,  9, 18], dtype=int64)

array([ -10, -282,   -8,   24,   38,    2,   45], dtype=int64)

array([-42,  27,  24,   7,  28,   0,  32], dtype=int64)

array([20, -4, 18, 38, 11, 27, 40], dtype=int64)

array([-19,  40,  30,  -1,  35,  20,  83], dtype=int64)

array([  19,   37,   18,   20,   24, -123,   20], dtype=int64)

array([ -6,  20,  44,  35, -56,  -9,  49], dtype=int64)

array([   8,   29,   30, -209,   26,  -12,   35], dtype=int64)

array([  26,    0, -544,   -3,   12,   19,   49], dtype=int64)

array([ 20, 189,  28,  15,  -3,  61,  20], dtype=int64)

array([-147,   32,   21,   18,   10,   44,   20], dtype=int64)

array([-7, 51, 22, 16, 17, 38, 13], dtype=int64)

array([  20,   20,   60,  -12,   39,   24, -173], dtype=int64)

array([ -3,  20,  38,  16,  28, -15,  28], dtype=int64)

array([  36,   16,   19,   26, -397,   22,   17], dtype=int64)

array([ 28,  24,  26, 321,  28,  31,   9], dtype=int64)

array([  29,   13, -197,   29,   28,   17,   -9], dtype=int64)

array([  46, 1679,   10,   34,   79,  -70,   72], dtype=int64)

array([-1791,    -4,    70,    29,    32,    23,    24], dtype=int64)

array([-10,  50,  28, -10,  51,  17,  -4], dtype=int64)

array([ 38,  18,  21,  13,  12,  -5, 764], dtype=int64)

array([  50,  -49,   52,    1,   28, -697,    0], dtype=int64)

array([ -20,   16,   -3,   23, 1553,    0,    5], dtype=int64)

array([   27,    -6,    51, -1772,    -6,    27,    23], dtype=int64)

array([22, -1, 71,  5, 39, 21, -5], dtype=int64)

array([  29, -210,   21,   24,   17,   34,   21], dtype=int64)

array([-205,   32,  -21,   54,   31,   21,   17], dtype=int64)

array([-11,  26,  24,  63,   6,  27,  10], dtype=int64)

array([ -11,   23,   40,   20,   41,   11, -140], dtype=int64)

array([  29,   20,   43,   34,    6, -233,  -11], dtype=int64)

array([ 57,  11,  20,  19,  14,  33, -10], dtype=int64)

array([   11,    28,    26, -1057,    -3,     6,     8], dtype=int64)

array([  4,   6, 624,  23,  -7,  15,  61], dtype=int64)

array([  19, -399,   -6,   17,   15,   38,   11], dtype=int64)

array([166,  24,  15,  14,  40,   6,  32], dtype=int64)

array([ 7,  7, 30,  9, 25, 26,  8], dtype=int64)

array([ -11,   21,   20,   48,   22,   11, -256], dtype=int64)

array([  3,  39,  10,  15,   4, 126,  -5], dtype=int64)

array([  35,   11,   45,   15, -384,   -8,   20], dtype=int64)

array([  40,   21,   -2, -213,   13,   -2,   15], dtype=int64)

array([ 40,  27, 283, -10,  44,  29,   7], dtype=int64)

array([  28, -158,   23,   37,   18,   -3,   70], dtype=int64)

array([324,  19,   1,  73, -15,  63,  39], dtype=int64)

array([15,  0, 63,  4, 36, 32, 27], dtype=int64)

array([  24,   25,   65,    1,   37,   25, -229], dtype=int64)

array([ 45, -29,  36,   2,  24,  79,  -7], dtype=int64)

array([  70,    0,   41,   28, -463,   11,    7], dtype=int64)

array([  9,  12,  23, 128,  30,   9,   2], dtype=int64)

array([  22,   10, -256,  -10,   26,   31,   53], dtype=int64)

array([  38, -268,   21,   -7,   26,   20,   50], dtype=int64)

array([-198,   25,    3,   22,    3,   31,   41], dtype=int64)

array([-3, 14, 20, 27, 52, 25, 23], dtype=int64)

array([-13,  22,  55,   6,  25,  21,  83], dtype=int64)

array([  17,  -10,   35,    3,   63, -330,   22], dtype=int64)

array([-1, 21, 51, 23, 56,  1, 21], dtype=int64)

array([ 53,  36,  14, -57,  30, -19,  31], dtype=int64)

array([   7,   29, -619,   25,  -10,   17,   48], dtype=int64)

array([ 17, 166,  -6,  23,  29,  18,  38], dtype=int64)

array([-94,  35, -11,  19,  25,  33,  42], dtype=int64)

array([ -7,  20,  20,  54,  18, -22,  52], dtype=int64)

array([  27,   41,   46,    6,  -11,   29, -393], dtype=int64)

array([  11,   40,   27,   23,    8, -158,   -5], dtype=int64)

array([33, -2, 27, 22, 72, 27, -9], dtype=int64)

array([  25,   38,   16, -231,   12,   -2,   30], dtype=int64)

array([  9,   1, 262,   3,  60,  -9,  16], dtype=int64)

array([  31, -131,  -13,   27,   41,   52,   40], dtype=int64)

array([ 34, -13,  70,   0,  18,  74,  26], dtype=int64)

array([ 37,  40, -19,  78, -25,  39,  67], dtype=int64)

array([  38,   26,   47,   10,   47,   38, -388], dtype=int64)

array([  47,   41,   22,   27,   34, -740,   -3], dtype=int64)

array([ 31,  -9,  41,  32, 329, -13,  35], dtype=int64)

array([  26,   27,  -22, -580,   -5,   32,   34], dtype=int64)

array([ 19, -17, 127,  -2,  66,  21,  36], dtype=int64)

array([  24, -695,   -6,   29,   28,   34,  -18], dtype=int64)

array([-142,   -7,   21,   33,    6,   38,   21], dtype=int64)

array([ 23,   2,  17,  28, -13,  23,  32], dtype=int64)

array([ -10,   40,   -1,   51,   12,    9, -208], dtype=int64)

array([ 25,  49,   5,  20,  30, -84,  16], dtype=int64)

array([ 33,  19,  32,  26, 268,   0,  40], dtype=int64)

array([ -20,   56,   40, -675,   12,   31,   15], dtype=int64)

array([  37,   19, -176,  -13,   22,   46,   24], dtype=int64)

array([   0, -121,   19,   26,    5,   35,    8], dtype=int64)

array([-91, -10,  26,  40,  18,  25,  18], dtype=int64)

array([36, 42, 30, 35, 32, 26, 39], dtype=int64)

array([   43,    35,    49,    45,   -26,   101, -1751], dtype=int64)

array([  7,  38,   9, -12,  57, 158,   4], dtype=int64)

array([34, 27, 24, 29, -1, 25, 35], dtype=int64)

array([  79,   23,   32, -518,   17,   34,  -13], dtype=int64)

array([24, 28, 85, 25, 45, 23, -3], dtype=int64)

array([  32, -742,    6,   42,    4,    4,   47], dtype=int64)

array([-269,    2,   20,   29,    5,   31,   16], dtype=int64)

array([ 3, 15, 10, 20, 25, 35, 20], dtype=int64)

array([ 42,  19,  28, -19,  46,  31, 487], dtype=int64)

array([  12,   95,   23,  -21,   76, -431,    5], dtype=int64)

array([  33,   22,   63,    8, -148,   10,   47], dtype=int64)

array([  46,   33,   32, -656,   24,   -2,   26], dtype=int64)

array([34, 22, 11, 36,  6,  2, 37], dtype=int64)

array([ 22, 130,  32, -12,  38,  67,  28], dtype=int64)

array([-373,   32,   25,   21,   24,   21,   21], dtype=int64)

array([19, -6, 31,  3, 35, 15, 16], dtype=int64)

array([ 49,  25,  22,   6,  -9,  35, -79], dtype=int64)

array([   4,   18,   42,   18,  -12, -114,   -7], dtype=int64)

array([  17,   34,   20,    2, -143,   -8,   19], dtype=int64)

array([   8,   25,   22, -357,    2,   13,   26], dtype=int64)

array([ 39,  18, -80,  23,  16,   5,  36], dtype=int64)

array([ 20, 203,  -8,  59,  11,   5,  25], dtype=int64)

array([-277,   -6,   49,   12,    9,   39,   -6], dtype=int64)

array([ 34,  12,  28,  49,  19, -17,  43], dtype=int64)

array([ 24,   0,  54,  18,  19,   9, -57], dtype=int64)

array([  30,   54,    1,   20,   20, -347,   22], dtype=int64)

array([ -7,  45,  16,  20, -43,  25,  18], dtype=int64)

array([  54,   -8,   43, -384,   -7,   30,   12], dtype=int64)

array([ 8, -5, 15,  5,  5, 14, 21], dtype=int64)

array([20, 74, 10, 38, 18, -6, 40], dtype=int64)

array([157, -13,  46,  46,   5,   8,  62], dtype=int64)

array([-10,  46,  13,  22,   7,  13,  -6], dtype=int64)

array([ 34, -12,  48,  19, -19,  49, 247], dtype=int64)

array([  42,  -10,   28,   46,   29, -800,    3], dtype=int64)

array([ -4,   7,  42,   0, 867,  30,  30], dtype=int64)

array([  28,   20,   35, -698,  -11,   62,    2], dtype=int64)

array([ 20, -11,  95,  21,  39, -24,  74], dtype=int64)

array([ -11, -321,   -8,   31,   36,  -26,   50], dtype=int64)

array([-140,    1,   14,   56,   -6,   41,   25], dtype=int64)

array([-8, 38, 17, 19, 16, 13, -5], dtype=int64)

array([  27,   19,   -4,   54,   28,   27, -558], dtype=int64)

array([  10,    3,   37,   16,   22, -200,   19], dtype=int64)

array([ 23, -11,  35,  22, 519, -21,  72], dtype=int64)

array([  31,   56,   40, -509,   24,   -9,   26], dtype=int64)

array([ 20,  25,   3, -11,  65,  16,  43], dtype=int64)

array([  59, -520,    3,   40,    2,    4,   18], dtype=int64)

array([-89, -12,  40,   8,  14,  45, -12], dtype=int64)

array([ -3,  36,  19,  20,  16, -11,  40], dtype=int64)

array([   32,    57,   -35,    33,     3,    43, -1142], dtype=int64)

array([  17,   -7,   53,   19,   -9, 1353,  -11], dtype=int64)

array([  -18,    50,    18,    52, -1743,    -3,    15], dtype=int64)

array([ 21,  36,  -2, 136,  32,  12,  38], dtype=int64)

array([  61,   28, -467,   24,   24,   15,   28], dtype=int64)

array([20, 72, 26, 24, 25, 32, -5], dtype=int64)

array([-109,   30,   29,    6,   -1,   51,   15], dtype=int64)

array([ -7,  19,  45,  39,   7, -10,  44], dtype=int64)

array([17, 30,  6, 24, 33, 19, 95], dtype=int64)

array([  2,  44,  -2,  38,  16, -36,   2], dtype=int64)

array([  61,   21,   21,   20, -243,   26,   21], dtype=int64)

array([  32,   30,   27, -138,   21,   27,   -7], dtype=int64)

array([   4,   37, -138,   -1,   53,   18,   -7], dtype=int64)

array([ 55, 340,   8,  60, -13,  65,  31], dtype=int64)

array([-617,   -4,   46,   29,   -7,   13,   26], dtype=int64)

array([-13,  44,   5,  25,  21,  46,  28], dtype=int64)

array([19,  7, 29, 53, 26, 28,  1], dtype=int64)

array([  29,  -18,   49,   18,    1, -804,   -6], dtype=int64)

array([  19,    0,   28,    5, -508,   -2,    6], dtype=int64)

array([  6,   2,   9, 725,  27,  -6,  41], dtype=int64)

array([  28,   -8, -123,   -5,   43,   -5,   17], dtype=int64)

array([ 21, -88,  23,  30,  16,  -7,  49], dtype=int64)

array([-169,   18,   26,   -7,   17,   35,   42], dtype=int64)

array([-6, 29,  0, 15, 32,  2,  2], dtype=int64)

array([ 60,  13,  23,  39,  21,  -1, -61], dtype=int64)

array([  23,   17,   29,   49,   32, -200,  -13], dtype=int64)

array([  19,   48,   28,   32, -359,   30,   32], dtype=int64)

array([  11,   38,    5, -118,   30,   30,   20], dtype=int64)

array([  46,   29, -865,   16,   -6,   13,   36], dtype=int64)

array([ -2, 178,  25,  13,  16,  -3,  37], dtype=int64)

array([-122,   23,   -7,   25,   39,   10,   10], dtype=int64)

array([-8, 39, 29, -9, 43, 29, 18], dtype=int64)

array([  5,  60,  -7,  28,  45,  26, 175], dtype=int64)

array([  51,   11,   54,   44,   34, -880,   22], dtype=int64)

array([21,  8, 21, 24,  1, -3, 25], dtype=int64)

array([-17,  40,  17, 289,   5,  11,  41], dtype=int64)

array([  34,   31, -493,   16,    2,   52,    3], dtype=int64)

array([   2, -423,   21,   19,    4,   31,   -3], dtype=int64)

array([-229,   21,   -7,   16,   12,   23,   27], dtype=int64)

array([23,  9, 16, 32, -1, 28, 12], dtype=int64)

array([ 11,  28,  29,   0,  27,   9, -40], dtype=int64)

array([  50,   12,    6,   41,   41, -224,   -8], dtype=int64)

array([ 54,  20,  18, -11, -36,  31, -15], dtype=int64)

array([ -10,   56,   32, -134,   -8,   27,   55], dtype=int64)

array([  19,   25, -270,   30,   23,   17,  -10], dtype=int64)

array([  36, -227,   24,   -9,   24,   43,  -12], dtype=int64)

array([163, -14,  28,  39,  57,  25,  23], dtype=int64)

array([-9, 23, 42,  6, 55, 19, 23], dtype=int64)

array([  -9,   37,   -7,   40,   25,   -6, -242], dtype=int64)

array([ 15,  21,   9,  18,  11, 468,  12], dtype=int64)

array([  32,   16,   24,  -13, -144,    9,   54], dtype=int64)

array([  59,  -23,   67, -716,    8,   29,   -3], dtype=int64)

array([ 22,  10, 276,   5,  13,  27,  38], dtype=int64)

array([  28, -531,   10,   -1,   15,   50,   12], dtype=int64)

array([154,   5,  31,   6,  40,  14,  35], dtype=int64)

array([14, 25,  4, 29, 17, 34, 18], dtype=int64)

array([  20,   17,   27,   37,  -11,   44, -375], dtype=int64)

array([  1,  24,  10,   6,  22, 683,  -9], dtype=int64)

array([ 13,  39,   3,  50, 383,  31,  35], dtype=int64)

array([  98,   34,   25, -959,   22,   30,   18], dtype=int64)

array([  16,   24, -586,   18,   22,   -2,   35], dtype=int64)

array([ 15, 102,  27,  20,  20,  32,   0], dtype=int64)

array([-182,    2,   28,   22,   40,    5,    0], dtype=int64)

array([18,  0, 27, 24, 13, 12, 20], dtype=int64)

array([  13,   24,   -3,   37,   40,   27, -160], dtype=int64)

array([  29,   30,  -10,   38,   26, -270,  -11], dtype=int64)

array([ 10,  49, -12,  49,  55,  34,  -8], dtype=int64)

array([  40,   19,   26, -333,    6,    7,   52], dtype=int64)

array([ 32,  16, 471,  13,  14,  61,  24], dtype=int64)

array([  27, -515,    6,   54,  -14,   58,   15], dtype=int64)

array([-467,    7,   45,   14,   -4,   37,   32], dtype=int64)

array([ 8, 50, 15, -4, 26, 46,  2], dtype=int64)

array([  8,  23,  11,  15,  38,  23, 140], dtype=int64)

array([  38,   24,   32,    7,   30, -358,   -3], dtype=int64)

array([ 22,  20,   3,  27, 136,  29,  18], dtype=int64)

array([  17,  -13,   51, -280,   28,   -6,   18], dtype=int64)

array([ 19,  58, 247,  28,  27,  19,   5], dtype=int64)

array([  30, -341,   22,   -7,   24,   62,  -13], dtype=int64)

array([-136,   31,   31,   13,   -4,   20,   51], dtype=int64)

array([ 25,   4,  30,  -8,  48, -13,  29], dtype=int64)

array([  40,   34,   11,   71,   26,   30, -834], dtype=int64)

array([ 19,  41, -12,  42,  -7, 463, -14], dtype=int64)

array([  20,   63,   30,   23, -772,   19,   -6], dtype=int64)

array([ -15,   13,   40, 1158,   16,   10,   94], dtype=int64)

array([  -26,    93, -1199,    11,    36,    20,    25], dtype=int64)

array([  -8, -182,    5,    6,   29,   17,   54], dtype=int64)

array([118,  12,   5,  27,  23,  62,  27], dtype=int64)

array([  5,  38,  18, -12,  17,  47,  29], dtype=int64)

array([  55,   18,   -9,   24,   38,    3, -183], dtype=int64)

array([ 57,  27,  21,  -3,   9, 494, -14], dtype=int64)

array([    6,    84,    29,    22, -1437,    -2,    25], dtype=int64)

array([  11,   27,    3, -249,   -6,   13,   23], dtype=int64)

array([ 11,  14, 535,   9,  11,   9,  60], dtype=int64)

array([  -5, -164,    5,   14,   12,   27,   13], dtype=int64)

array([1034,   14,   69,   45,   -3,   33,   94], dtype=int64)

array([ 6, 36, -6, 43, 12, 16,  4], dtype=int64)

array([   14,    39,    47,    86,    50,    40, -1477], dtype=int64)

array([  20,    8,   32,   30,    8, -375,   -7], dtype=int64)

array([ 18,   9,  24,   9, 109, -11,  57], dtype=int64)

array([  14,   19,   51, -124,  -11,   44,   19], dtype=int64)

array([-8, 28, 40, -5, 53, 13, 42], dtype=int64)

array([  50, -234,   -6,   34,   26,   -5,   54], dtype=int64)

array([-45, -10,  62,  -2,  13,  62,  17], dtype=int64)

array([ 17,  19,   7,  -2,  43, -17,  29], dtype=int64)

array([ 19,   1,  41,  11,  18,  18, 245], dtype=int64)

array([  25,   25,   31,   33,    6, -671,   -6], dtype=int64)

array([ 45,  18,  12,  11, 648,  36,  21], dtype=int64)

array([  78,   23,    0, -159,   38,   13,   40], dtype=int64)

array([  67,   35, -697,  -10,   58,   17,   -7], dtype=int64)

array([  20, -276,   26,  -12,   23,   47,  -18], dtype=int64)

array([-104,   -6,   20,   27,   43,   14,  -12], dtype=int64)

array([-12,  55,  18,  26, -18,  48,  24], dtype=int64)

array([  18,   45,   -2,   16,   25,   64, -286], dtype=int64)

array([ 54,  -3,  55, -15,  51,  69,   9], dtype=int64)

array([  43,  -20,   64,   -8, -509,    6,    5], dtype=int64)

array([ 25,  33,   8, 281,  14,  10,  28], dtype=int64)

array([  23,   28, -124,   12,    4,   48,   52], dtype=int64)

array([  21, -405,    1,   18,   23,   70,   19], dtype=int64)

array([-79,   2,  33,  31,  42,  28,   5], dtype=int64)

array([ -8,  37,  37,  51,  18, -15,  25], dtype=int64)

array([  25,  -11,   61,    4,   26,   18, -414], dtype=int64)

array([ 23,  42,  13, -10,  18, 208,  31], dtype=int64)

array([  -4,   16,   49,   23, -386,   -1,    9], dtype=int64)

array([   6,   44,    1, -281,   -3,   36,   13], dtype=int64)

array([ -7,  33, 251,  -4,  18,  51,  -8], dtype=int64)

array([ 28, 175, -16,  38,  59,  37,   4], dtype=int64)

array([-154,  -17,   34,   21,   82,   26,   -1], dtype=int64)

array([-9, 61,  6, 10, 47, 30, 21], dtype=int64)

array([  17,   49,   30,    9,   23,   -4, -449], dtype=int64)

array([-15,  19,  38, -10,  13,   6,  -7], dtype=int64)

array([ 29,   3,  22,   2, 107,  -5,  35], dtype=int64)

array([  23,   43,   16, -102,   19,    0,   16], dtype=int64)

array([ 44,  30, -21, -11,  64,  16,  33], dtype=int64)

array([  0, 859,  48,  45, -11,  26,  91], dtype=int64)

array([-1143,   -11,    42,    42,    38,   -11,    44], dtype=int64)

array([-12,  28,  40,  35,  48,  23,  -9], dtype=int64)

array([ 10,   2,  56,   6,  19,  14, 118], dtype=int64)

array([ 26,  44,   8,  32,  18, -79, -12], dtype=int64)

array([  28,   33,   65,   16, -700,   27,    5], dtype=int64)

array([ 22,  20,  13, -40,  -9,  54,  16], dtype=int64)

array([  17,   24, -219,   -8,   17,   48,   30], dtype=int64)

array([ 12, -62,  -7,  23,  19,  21,  55], dtype=int64)

array([222,  34,  -9,  24,  64, -17,  30], dtype=int64)

array([ 6, 46, 11, -5, 31, 47, 30], dtype=int64)

array([   29,     6,    -1,    64,    25,    21, -1026], dtype=int64)

array([11, 16, -7, 18, 10], dtype=int64)

IndexError: index 6 is out of bounds for axis 0 with size 5

In [65]:
predictions

[361.56249370530787,
 -400.47357935679696,
 195.74463557368335,
 -4051.6377154233824,
 45.178010471204189,
 -219.2685519476891,
 2140.903826266805,
 704.89819757712746,
 754.74319693610187,
 2495.6055723525578,
 -16.035782226650984,
 11207.814381688262,
 -6396.6578081190928,
 145.18675367047308,
 -504.19860602141301,
 254.9524779355076,
 82.405844155844179,
 21834.475987193182,
 470.38213356209184,
 -150.96969463887396,
 -726.87274150807059,
 -1896.724090583004,
 969.48852929127418,
 673.63107678328015,
 410.87020541719704,
 6024.9319012797096,
 -2323.9543421127273,
 -934.99618638659365,
 -49.919697486083379,
 789.97065239855783,
 249.88071298881317,
 572.57745593462141,
 96.481868469575957,
 783.14102564102586,
 445.56074766355147,
 146.47866298880407,
 -118.32960647701928,
 -875.73923697107034,
 1967.5990740740747,
 -154.63948421391348,
 850.97879251050858,
 79483.800607082609,
 -16.967638876150254,
 -3190.9582888590307,
 -85.730163226876144,
 4520.9807020462504,
 94.072470787673382,

In [54]:

X = difference(Series_tract[9*0:9*0+8] )
X
model = AR(X)
model_fit = model.fit(maxlag=1, disp=False)
window = model_fit.k_ar
coef = model_fit.params
    # walk forward over time steps in test
history = X[6]   
predictions =  coef[0]+coef[1]*X[6]  

array([29, -6, 37, 42,  9, 28, 12], dtype=int64)

In [55]:
predictions

25.072615570550926

### predictions